create database customer_behavior;
use customer_behavior;
SELECT 
    *
FROM
    customer;
SELECT 
    COUNT(*)
FROM
    customer;


-- Q1. What is the total revenue generated by male vs. female customers?
SELECT 
    gender, SUM(purchase_amount) AS revenue
FROM
    customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT 
    customer_id, purchase_amount
FROM
    customer
WHERE
    discount_applied = 'Yes'
        AND purchase_amount >= (SELECT 
            AVG(purchase_amount)
        FROM
            customer);

-- Q3. Which are the top 5 products with the highest average review rating? 
SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS 'average product rating'
FROM
    customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT 
    shipping_type, AVG(purchase_amount) AS revenue
FROM
    customer
WHERE
    shipping_type IN ('Standard' , 'Express')
GROUP BY shipping_type;
-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.

SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    AVG(purchase_amount) AS 'avg revenue',
    SUM(purchase_amount) AS 'total revenue'
FROM
    customer
GROUP BY subscription_status;
SELECT 
    *
FROM
    customer;
-- Q6 Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    ROUND(SUM(CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END) / COUNT(*) * 100,
            2) AS discount_rate
FROM
    customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
-- Q7 segment customers into new , returning and loyal based on their 
-- total number of previous purchases and show the count of each segment
with customer_type as(
select customer_id , previous_purchases,
case
    when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'loyal'
end as customer_segment
from customer
)
select customer_segment, count(*) as "Number of customers "
from customer_type
group by customer_segment;
-- Q8 What are the top 3 most purchased products within each category?
with item_counts as(
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id)desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank<=3;
-- Q9 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

-- Q10 what is the revenue contribution of each age group?

SELECT 
    age_group, SUM(purchase_amount) AS revenue
FROM
    customer
GROUP BY age_group
ORDER BY revenue DESC;






